name: Zagreb Music Sync

on:
  schedule:
    - cron: '34 11 * * *'
    - cron: '45 22 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Uses the built-in secret for permission

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        run: python zg_event.py
      
      - name: Commit and Push
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add zagreb_gigs.ics events.csv
          
          # This 'pull' command syncs the Bot with any changes you made in the browser
          git pull --rebase origin main
          
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update Calendar & CSV"
            git push origin main
          fi
