name: Zagreb Music Sync

on:
  schedule:
    - cron: '34 11 * * *'
    - cron: '45 22 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Important for pushing the file
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v5 # Updated to v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        run: python zg_event.py

      - name: Commit and Push Calendar
        run: |
          git config --global user.name "Zagreb-Bot"
          git config --global user.email "bot@github.com"
          git add zagreb_gigs.ics
          # The '|| exit 0' ensures the script doesn't fail if there are no new concerts to add
          git commit -m "Automated Calendar Update" || exit 0
          git push
